- name: "install Jmeter and selenium"
  hosts: vm-azure
  remoteuser: VMTest

  tasks:
    
    - name: install prerequisites Jmeter and selenium
      become: yes
      apt: 
        force_apt_get: yes
        pkg:
         - openjdk-8-jdk
         - wget
         - zip
         - unzip
         - python3
         - python3-pip
      


    - name: download Jmeter
      shell: cd /opt && wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.4.3.zip

    - name: unzip Jmeter
      shell: cd /opt && unzip apache-jmeter-5.4.3.zip

    - name: install selenium
      shell: pip3 install selenium
      
    - name: download google-chrome
      shell: cd /opt && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

    - name: install google-chrome
      shell: cd /opt && sudo dpkg -i google-chrome-stable_current_amd64.deb

    - name: download chromdriver
      shell: cd /opt && wget https://chromedriver.storage.googleapis.com/99.0.4844.51/chromedriver_linux64.zip

    - name: unzip chromedriver
      shell: cd /opt && unzip chromedriver_linux64.zip
      
    - name: change ownership of chromedriver to Root
      shell: sudo chown root:root /usr/bin/chromedriver
      
    - name: give VMTest execute permission
      shell: sudo chmod +x /opt/chromedriver
      
      
      #register: "output"
    #- debug: var=output.stdout_lines 
      

  