- name: "run petclinic docker container"
  hosts: all
  user: VMTest
  become: true
  tasks:  
    #- name: Start container
      #become: yes
      #docker_container:
        #name: Test_container
        #image: juan8295/clinic_tomcat:1.0
        #command: docker run -itd -p 8090:8080 clinic_tomcat:1.0 /bin/bash
        

    - name: ensure a container is running
      become: true
      docker_container:
        name: TestContainer
        state: started
        image: juan8295/clinic_tomcat:1.0
        pull: true
        ports:
          - "8080:8999"
