- name: "run petclinic docker container"
  hosts: all
  user: VMTest
  become: true
  tasks:  

    - name: Log into DockerHub
      become: true
      docker_login:
        username: "{{ username }}"
        password: "{{ password }}"
    
    - name: Pull default Docker image
      docker_image:
        name: "juan8295/clinic_tomcat:1.0"
        source: pull
            

    - name: ensure a container is running
      become: true
      docker_container:
        name: TestContainer
        state: started
        image: juan8295/clinic_tomcat:1.0
        pull: true
        published_ports: 8090:8080
