- name: "stop docker container"
  hosts: all
  user: VMTest
  tasks:

  - name: Stop container
    become: yes
    docker_container:
      name: TestContainer
      image: juan8295/clinic_tomcat:1.0
      state: stopped