# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- Petclinic

pool:
  name: vm-azure 

steps:

# task: AzureCLI@2
  #displayName: login to AzureCLI
  #inputs:
    #azureSubscription: 'azure-cli-2022-04-01-09-22-56'
    #scriptType: 'bash'
    #scriptLocation: 'inlineScript'
    #inlineScript: 'az account show'

- task: TerraformCLI@0
  displayName: Terraform Init
  inputs:
    command: 'init'
    workingDirectory: $(TERRAFORM_DIR)
    allowTelemetryCollection: true
    commandOptions: -reconfigure
- task: TerraformCLI@0
  displayName: Terraform Validate
  inputs:
    command: 'validate'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  displayName: Terraform Plan
  inputs:
    command: 'plan'
    environmentServiceName: $(AZURE_CLI_SERVICE_PRINCIPAL)
    providerAzureRmSubscriptionId: $(SUBSCRIPTIONID)
    #runAzLogin: true
    commandOptions: -lock=false
    allowTelemetryCollection: true
    #publishPlanResults: 'tfplan'
    workingDirectory: $(TERRAFORM_DIR)

- task: TerraformCLI@0
  displayName: Terraform Apply
  inputs:
    command: 'apply'
    commandOptions: -lock=false
    workingDirectory: $(TERRAFORM_DIR)
    environmentServiceName: $(AZURE_CLI_SERVICE_PRINCIPAL)
    providerAzureRmSubscriptionId: $(SUBSCRIPTIONID)
    #runAzLogin: true
    allowTelemetryCollection: true

- task: Bash@3
  displayName: write out private key
  inputs:
    targetType: 'inline'
    script: 'terraform output -raw tls_private_key > ~/VMTest_rsa_key.pem && echo "write succesfull" && sudo chmod 600 ~/VMTest_rsa_key.pem'
    workingDirectory: $(TERRAFORM_DIR)

- task: Bash@3
  displayName: Store public IP of testVM in VMTest_public_IP
  inputs:
    targetType: inline
    script: terraform output -raw public_ip_address > ~/VMTest_public_IP
    workingDirectory: $(TERRAFORM_DIR)


- task: Bash@3
  displayName: present rsa key to authorized keys file of the testing environment, install some ansible dependencies
  inputs:
        targetType: 'inline'
        script: ansible-galaxy collection install community.docker && ansible-galaxy collection install ansible.posix && ansible-playbook add-key.yml --key-file=~/VMTest_rsa_key.pem -i ~/VMTest_public_IP
        workingDirectory: $(ANSIBLE_DIR)


#- task: Bash@3
  #displayName: Install ansible and terraform
  #inputs:
    #workingDirectory: 'petclinic_maven/provisioning/Ansible'
    #targetType: inline
    #script: ansible-playbook ansible-terraform-install.yml
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false


- task: Bash@3
  displayName: Install Docker 
  inputs:
    workingDirectory: $(ANSIBLE_DIR)
    targetType: inline
    script: ansible-playbook Docker-install.yml -i ~/VMTest_public_IP

- task: Bash@3
  displayName: docker login and create image
  inputs:
    targetType: 'inline'
    script: sudo docker login -u "juan8295" -p $(DOCKERPASSW) docker.io && ansible-playbook build-image.yml
    workingDirectory: $(ANSIBLE_DIR)
- task: Bash@3
  displayName: Start container
  inputs:
   workingDirectory: $(ANSIBLE_DIR)
   targetType: inline
   script: ansible-playbook --vault-password-file /home/azureuser/.ssh/password.txt Start-container.yml -i ~/VMTest_public_IP

- task: Bash@3
  displayName: execute-JMeter-test
  inputs:
    targetType: 'inline'
    workingDirectory: /opt/apache-jmeter-5.4.1/bin/
    script: |
      ./jmeter.sh -n -t /home/azureuser/myagent/_work/4/s/petclinic_maven/provisioning/TestPro.jmx -Jhost=$(cat ~/VMTest_public_IP ) -l /home/azureuser/myagent/_work/4/s/petclinic_maven/provisioning/testresults.jtl
- task: Bash@3
  displayName: execute push
  inputs:
    targetType: 'inline'
    workingDirectory: /home/azureuser/myagent/_work/4/s/petclinic_maven/provisioning
    script: |
            git pull git@github.com:Juan8295/Provisioning.git
            git checkout test
            git add testresults.jtl
            git commit -m "push" 
            git push git@github.com:Juan8295/Provisioning.git HEAD:Petclinic

- task: Bash@3
  displayName: Selenium-test
  inputs:
   targetType: 'inline'
   workingDirectory: /home/azureuser/myagent/_work/4/s/petclinic_maven/provisioning
   script: 
     pip install selenium ;
     python3 Selenium-test.py

- task: Bash@3
  displayName: stop docker container
  inputs:
    targetType: 'inline'
    workingDirectory: $(ANSIBLE_DIR)
    script: ansible-playbook Stop-container.yml -i ~/VMTest_public_IP

- task: TerraformCLI@0
  displayName: Terraform Destroy
  inputs:
    command: 'destroy'
    workingDirectory: $(TERRAFORM_DIR)
    commandOptions: -lock=false
    provider: 'azurerm'
    environmentServiceName: $(AZURE_CLI_SERVICE_PRINCIPAL)
    providerAzureRmSubscriptionId: $(SUBSCRIPTIONID)
    allowTelemetryCollection: true

- task: Bash@3
  displayName: docker login
  inputs:
    targetType: 'inline'
    script: sudo docker login -u "juan8295" -p $(DOCKERPASSW) docker.io

- task: Bash@3
  displayName: pull dockerimage
  inputs:
    targetType: 'inline'
    script: sudo docker pull juan8295/clinic_tomcat:1.0

- task: Bash@3
  displayName: Start Productie omgeving
  inputs:
    targetType: 'inline'
    script: sudo docker run -itd -p 8091:8080 juan8295/clinic_tomcat:1.0