# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- Petclinic

pool:
  name: vm-azure 

steps:

#- task: Maven@3
  #inputs:
    #mavenPomFile: 'pom.xml'
    #mavenOptions: '-Xmx3072m'
    #javaHomeOption: 'JDKVersion'
    #jdkVersionOption: '1.8'
    #jdkArchitectureOption: 'x64'
    #publishJUnitResults: true
    #testResultsFiles: '**/surefire-reports/TEST-*.xml'
    #goals: 'package'

- task: Bash@3
  displayName: Install ansible and terraform
  inputs:
    workingDirectory: 'petclinic_maven/provisioning/Ansible'
    targetType: inline
    script: ansible-playbook ansible-terraform-install.yml

- task: Bash@3
  displayName: Install Docker
  inputs:
    workingDirectory: 'petclinic_maven/provisioning/Ansible'
    targetType: inline
    script: ansible-playbook Docker-install.yml

- task: Bash@3
  displayName: docker login
  inputs:
    targetType: 'inline'
    script: sudo docker login -u "juan8295" -p $(DOCKERPASSW) docker.io
