# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- Petclinic

pool:
  name: vm-azure 

steps:

- task: AzureCLI@2
  displayName: login to AzureCLI
  inputs:
    azureSubscription: azure-cli-2022-04-01-09-22-56
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account show'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: 'petclinic_maven/provisioning/Terraform'

#- task: TerraformCLI@0
  #inputs:
    #command: 'plan'
    #environmentServiceName: 
    #providerAzureRmSubscriptionId: 
    #runAzLogin: true
    #allowTelemetryCollection: true
    #publishPlanResults: 'plan.tf'
    #workingDirectory: 'petclinic_maven/provisioning/Terraform'
    

#- task: TerraformCLI@0
  #inputs:
    #command: 'apply'
    #workingDirectory: 'petclinic_maven/provisioning/Terraform'
    #environmentServiceName: 
    #providerAzureRmSubscriptionId: 
    #runAzLogin: true
    #allowTelemetryCollection: true

#- task: Bash@3
  #displayName: Install ansible and terraform
  #inputs:
    #workingDirectory: 'petclinic_maven/provisioning/Ansible'
    #targetType: inline
    #script: ansible-playbook ansible-terraform-install.yml

#- task: Bash@3
  #displayName: Install Docker
  #inputs:
    #workingDirectory: 'petclinic_maven/provisioning/Ansible'
    #targetType: inline
    #script: ansible-playbook Docker-install.yml

#- task: Bash@3
  #displayName: docker login
  #inputs:
    #targetType: 'inline'
    #script: sudo docker login -u "juan8295" -p $(DOCKERPASSW) docker.io

#- task: Bash@3
  #displayName: pull dockerimage
  #inputs:
    #targetType: 'inline'
    #script: sudo docker pull juan8295/clinic_tomcat:1.0