- name: "Playbook to Add Key to azure VM's"
  hosts: all
  user: VMTest
  
  tasks:

  - name: "Copy the authorized key file from VM"
    ansible.posix.authorized_key:
      user: VMTest
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
