resource_group_name         = "pers-juan_goez_cordoba-rg"
resource_group_location     = "West Europe"
virtual_network_name        = "vnet-juan"
subnet_name                 = "subnet-juan"
public_ip_name              = "publicip-juan"
network_security_group_name = "nsg-juan"
network_interface_name      = "nic-juan"
linux_virtual_machine_name  = "linuxvm-juan"